SMTP 회원가입 메일인증 로직 구현
team-thicket/thicket-main-repository pull request #23
Opened 2023-11-20 03:11 UTC by SUPERK98

THICKET-9

2023-11-20 07:13 UTC, RunKaRin approved these changes

2023-11-20 07:22 UTC, ojs258 requested changes

2023-11-20 07:22 UTC, ojs258 commented on thicket-auth/src/main/java/com/example/thicketauth/smtp/dto/EmailPostDto.java
> +public class EmailPostDto {
dto 네이밍 컨벤션 맞춰주세요

2023-11-20 07:28 UTC, ejHA approved these changes
네이밍 맞춘 후 머지하시면 될 것 같읍니다~~~~

2023-11-20 07:36 UTC, ojs258 requested changes

2023-11-20 07:36 UTC, ojs258 commented on thicket-auth/src/main/java/com/example/thicketauth/smtp/config/redis/RedisConfig.java
> +        redisTemplate.setConnectionFactory(new JedisConnectionFactory(new RedisStandaloneConfiguration(redisHost, redisPort)));
개행 정리해주세요

2023-11-20 07:36 UTC, ojs258 commented on thicket-auth/src/main/java/com/example/thicketauth/smtp/controller/EmailController.java
> +                "email");
개행은 스트림 도트 연산자 기준으로해주세요

2023-11-20 07:36 UTC, ojs258 commented on thicket-auth/src/main/java/com/example/thicketauth/smtp/config/redis/RedisConfig.java
> +        redisTemplate.setConnectionFactory(new JedisConnectionFactory(new RedisStandaloneConfiguration(redisHost, redisPort)));
100글자가 넘을것 같으면 개행 할 수 있는 지점을 찾아보고 개행하기

2023-11-21 05:45 UTC, ojs258 approved these changes
죠습니다

2023-11-21 07:58 UTC, merged