(좌석) 프로젝트 셋팅 및 기본 CRUD 구현
team-thicket/thicket-main-repository pull request #34
Opened 2023-11-23 08:31 UTC by RunKaRin

THICKET-32

2023-11-23 09:13 UTC, ojs258 requested changes

2023-11-23 09:13 UTC, ojs258 commented on thicket-chair/src/main/resources/application.yml
> +  port: 7777
8000으로 해주세요 나중에 프론트 코드랑 연동해서 테스트할때 백 서버 포트 설정을 8000으로 해주고 테스트끝나고 나서 게이트웨이 서버가 연동 되었을때도 수정 없이 바로 테스트해 볼 수 있게

2023-11-23 11:23 UTC, RunKaRin commented on thicket-chair/src/main/resources/application.yml
> +  port: 7777
완료!

2023-11-23 12:05 UTC, ojs258 requested changes

2023-11-23 12:05 UTC, ojs258 commented on thicket-member/src/main/java/com/example/thicketmember/config/SwaggerConfig.java
> +                .addSecurityItem(new SecurityRequirement().addList("ApiKey"));
return new OpenAPI()
[tab2].components
[tab2].addSecur~
[tab2].addSecur~

이렇게 첫 개행에서 탭 두번으로 자리잡고 이후 점위치를 기준으로 정렬해주셔야합니다.

2023-11-23 12:12 UTC, ojs258 commented on thicket-member/src/main/java/com/example/thicketmember/config/SwaggerConfig.java
> +                .addSecurityItem(new SecurityRequirement().addList("ApiKey"));
바로 위에 메서드는 잘되어있는데 다른코드에도 중간 중간 잘못된거 있는지 한 번 만 검토해주세요~

2023-11-23 12:23 UTC, RunKaRin commented on thicket-member/src/main/java/com/example/thicketmember/config/SwaggerConfig.java
> +                .addSecurityItem(new SecurityRequirement().addList("ApiKey"));
완료!

2023-11-23 12:29 UTC, ojs258 approved these changes

2023-11-24 07:29 UTC, ojs258 requested changes

2023-11-24 07:29 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    }
서비스 메서드에서의 예외에 대한 익셉션 핸들러는 있는데
밸리데이션에 대한 익셉션 처리가 없습니다.
회원 레이어 컨트롤러 코드보면 익셉션 핸들러가 두개 일텐데 그거 참고해서 익셉션 핸들링 메서드 하나 더 구현해 주세요.

2023-11-24 07:38 UTC, ojs258 requested changes

2023-11-24 07:38 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    public ResponseEntity<?> findByUuid(@PathVariable String uuid) {
@PathVariable 다음에 @Notblank 이런식으로 바로 검증 어노테이션 붙히는 방식으로 검증해주는게 좋긴합니다.
ex ) @PathVariable @Notblank String uuid

2023-11-24 08:08 UTC, RunKaRin commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    }
완료!

2023-11-24 08:09 UTC, RunKaRin commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    public ResponseEntity<?> findByUuid(@PathVariable String uuid) {
완료!

2023-11-24 08:11 UTC, ojs258 approved these changes

2023-11-24 08:11 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    public ResponseEntity<?> findByUuid(@PathVariable String uuid) {
굳 좋슴다

2023-11-24 11:36 UTC, ojs258 requested changes

2023-11-24 11:36 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/domain/Chair.java
> +
좌석 관련 컬럼은 다있는데 공연 아이디가 없어요 어떤 공연의 좌석인지 알 수 있게 해야될거 같아요

2023-11-24 11:37 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/domain/Chair.java
> +
ERD 보고 해주세요

2023-11-24 12:38 UTC, RunKaRin commented on thicket-chair/src/main/java/com/example/thicketchair/domain/Chair.java
> +
완료!

2023-11-24 13:40 UTC, ejHA approved these changes
확인 완!!!

2023-11-26 06:34 UTC, SUPERK98 commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    }
조회를 uuid 로 한다면 등록시에 uuid 값을 반환해 줘야 할 것 같습니다!

2023-11-26 06:34 UTC, SUPERK98 approved these changes

2023-11-26 06:38 UTC, ojs258 approved these changes

2023-11-26 06:38 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/domain/Chair.java
> +
굳 좋슴다

2023-11-26 06:40 UTC, ojs258 approved these changes

2023-11-26 06:40 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    }
등록시에는 아무것도 반환안해도 조회시에 UUID가 리턴되니까 그거 활용해서 요청보내면 될 것 같아요

2023-11-26 06:42 UTC, ojs258 commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    }
등록시에는 아무것도 반환안해도 목록 조회시점에서 조회가능하니까 괜찮을거 같아요
등록 및 조회 관점은 관리자 입장이고 조회 및 사용 관점은 사용자 입장으로 서로 분리 되어있어서 괜찮을거 같습니다,

2023-11-26 06:50 UTC, SUPERK98 commented on thicket-chair/src/main/java/com/example/thicketchair/controller/ChairApiController.java
> +    }
목록 전체 조회 한번 해주고- > 개별조회로 들어가니까 상관없겠군요!

2023-11-26 06:54 UTC, merged